.github/workflows/build-main.yml
.github/workflows/daily-build.yml
build.gradle
gradle.properties
prometheus-extension-ballerina/Ballerina.toml
prometheus-extension-ballerina/build.gradle
prometheus-extension-ballerina/metric_reporter.bal

> Replace usages of stringutils APIs

Replace usages of stringutils APIs

---

prometheus-extension-ballerina/metric_reporter.bal

> Update to match the latest HTTP module changes

Update to match the latest HTTP module changes

---

prometheus-extension-ballerina/build.gradle

> Rename ballerina command to bal

Rename ballerina command to bal

---

README.md

> Add README content for enabling extension

Add README content for enabling extension

---

build.gradle
gradle.properties

Update lang version

---

grafana-dashboard.json

https://github.com/ballerina-platform/module-ballerinax-prometheus/issues/4
Ballerina Up / Down
Service metrics
Client metrics
Sql client metrics

Update Grafana dashboard to SwanLake alpha

---

build.gradle
gradle.properties
prometheus-extension-tests/src/test/java/io/ballerina/observe/metrics/prometheus/PrometheusMetricsTestCase.java

> Update dependencies to Ballerina Alpha 3 snapshots

Update dependencies to Ballerina Alpha 3 snapshots

---

prometheus-extension-ballerina/Dependencies.toml
prometheus-extension-ballerina/build.gradle

> Move dependencies to Dependencies.toml

Move dependencies to Dependencies.toml

---

gradle.properties
prometheus-extension-ballerina/build.gradle

Update dependency versions

---

prometheus-extension-tests/src/test/java/io/ballerina/observe/metrics/prometheus/PrometheusMetricsTestCase.java

> Update test cases to fit the latest service type name changes (Related to ballerina-platform/ballerina-lang#28776)

Update test cases to fit the latest service type name changes

---

prometheus-extension-ballerina/build.gradle

> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763

Add extracted bala in the zip artifact

---

gradle.properties

> Update ballerina lang version to the current standard library version

Update ballerina lang version to the current standard library version

---

build.gradle
prometheus-extension-ballerina/build.gradle

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Strip stdlib dependency version

---

.github/workflows/build-dev-branches.yml
.github/workflows/publish-release.yml

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Ignore dependency branch for push builds

---

prometheus-extension-tests/src/test/java/io/ballerina/observe/metrics/prometheus/PrometheusMetricsTestCase.java

> Update test cases
Related to: https://github.com/ballerina-platform/ballerina-lang/pull/30107

Update test cases

---

.github/workflows/build-dev-branches.yml
.github/workflows/build-main.yml
.github/workflows/pull-request.yml

> Add step to publish bala to the action run

Add step to publish bala to the action run

---

.github/workflows/build-main.yml

Standardise Build Name

---

prometheus-extension-ballerina/metric_reporter.bal

> Improve string concatenations in metric reporter using string templates and string arrays.
Related to: https://github.com/ballerina-platform/ballerina-lang/issues/22820

Improve string concatenations in metric reporter

---

prometheus-extension-tests/src/test/java/io/ballerina/observe/metrics/prometheus/PrometheusMetricsTestCase.java

Fix build failure

---

.github/workflows/daily-build.yml
.github/workflows/graalvm-check.yml
gradle.properties
prometheus-extension-ballerina/Ballerina.toml

Add graalvm check for native build

---

.github/workflows/graalvm-check.yml

Fix updating versions in graalvm check

---

.github/workflows/build-dev-branches.yml
.github/workflows/build-main.yml
.github/workflows/central-publish.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
prometheus-extension-ballerina/Ballerina.toml
prometheus-extension-ballerina/build.gradle

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Fix issues with Java version and Gradle incremental build

---

prometheus-extension-ballerina/build.gradle

$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Fix publishing maven artifacts

---

.github/workflows/build-dev-branches.yml
.github/workflows/build-main.yml
.github/workflows/daily-build.yml

$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Fix uploading code coverage report

---

gradle.properties

$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Update version to `1.0.0`
